LANDSAT_COEFFICIENT_NAMES = ['BAND_1', 'BAND_2', 'BAND_3', 'BAND_4', 'BAND_5', 'BAND_6', 'BAND_7', 'BAND_ST_B10', 'THERMAL_RADIANCE', 'UPWELL_RADIANCE', 'DOWNWELL_RADIANCE', 'ATMOSPHERIC_TRANSMITTANCE', 'EMISSIVITY', 'EMISSIVITY_STDEV', 'CLOUD_DISTANCE', 'QUALITY_L2_AEROSOL', 'QUALITY_L2_SURFACE_TEMPERATURE', 'QUALITY_L1_PIXEL', 'QUALITY_L1_RADIOMETRIC_SATURATION', "NDVI", "EVI", "NDWI-Green"]
FORMULAS = {
    "NDVI": "(BAND_5 - BAND_4) / (BAND_5 + BAND_4)",
    "EVI": "2.5 * (BAND_5 - BAND_4) / (BAND_5 + 6 * BAND_4 - 7.5 * BAND_2 + 1)",
    "NDWI-Green": "(BAND_3 - BAND_5) / (BAND_3 + BAND_5)",
}
